### ISSUE TITLE
[Bug]: No longer shows link to created pull request

### ISSUE THREAD

**Issue by sitiom** [russellbanks/Komac#133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When running `Komac update`, Komac should show a link to the pull request at the end of the command:
![image](https://user-images.githubusercontent.com/56180050/224997011-04e67176-ed9f-4adc-8df0-2514ea43fb8d.png)

However, this is no longer showing in the latest version. Example with https://github.com/LGUG2Z/whkd/actions/runs/4411818940/jobs/7730689700:
![image](https://user-images.githubusercontent.com/56180050/224997142-1ba8ef6f-cb4b-4751-97ac-219eb41dfa90.png)
Despite that, the PR is successfully created: https://github.com/microsoft/winget-pkgs/pull/99400

**Comment by russellbanks** [comment]
Sorry about this - I extracted the part that prints the link to the pull request from the function that creates the pull request so that it had less dependencies and was easier to test, but forgot to add it back in when the `--submit` flag has not been used (which winget releaser uses). It should still print that when `--submit` is not used.

Fixed in #134
