### ISSUE TITLE
[Bug]: The number of unique installer urls is greater than the number of previous manifest urls

### ISSUE THREAD

**Issue by chrisbra** [russellbanks/Komac#224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi,
with the latest vim.vim releases, it fails with the mentioned error message: "The number of unique installer urls is greater than the number of previous manifest urls"

Don't know what this means :/ 

https://github.com/vim/vim-win32-installer/actions/runs/5339923565/jobs/9679145176

I am not sure if this is related, but apparently the latest released winget-packages version used the same installer for x86 as well as x64 which looks wrong. https://github.com/microsoft/winget-pkgs/blob/master/manifests/v/vim/vim/9.0.1632/vim.vim.installer.yaml

**Comment by russellbanks** [comment]
I believe this is related to (and fixed by) https://github.com/vedantmgoyal2009/winget-releaser/issues/173#issuecomment-1632250129, as when `Win32` was added as an architecture to look for in URLs because of https://github.com/russellbanks/Komac/issues/215#issue-1758310592, Vim's installers started to be identified as x86 because of the win32 in `https://github.com/vim/vim-win32-installer/releases/download/v9.0.1672/gvim_9.0.1672_x64.exe`. This meant that Komac had trouble matching them and inadvertently matched the x64 installer twice.

Therefore, the unique amount of previous installer URLs was only 1 (because the same URL was used for both installers), meaning it was less than the number of URLs provided (2).

Because of this issue, I've removed the block of code that does this check and fixed the architecture identification as described in https://github.com/vedantmgoyal2009/winget-releaser/issues/173#issuecomment-1632250129.
