### ISSUE TITLE
[Feature/Idea]: Add ignore SSL certificate verification

### ISSUE THREAD

**Issue by CoolPlayLin** [russellbanks/Komac#225]
When I was using tools like [Fastgithub](https://github.com/dotnetcore/FastGithub) to speed github, Following information has appeard.

![image](https://github.com/russellbanks/Komac/assets/96709586/7a60ba00-a6f8-4118-aa8f-498ac5eb4f6d)

It should be an issue with the tool using a self-signed certificate, could you add an option to ignore certificate validation to fix this?

**Comment by CoolPlayLin** [comment]
@russellbanks 
![image](https://github.com/russellbanks/Komac/assets/96709586/d0f15415-1954-4c57-a39d-5ba3a0046cab)

**Comment by russellbanks** [comment]
> @russellbanks ![image](https://user-images.githubusercontent.com/96709586/251356900-d0f15415-1954-4c57-a39d-5ba3a0046cab.png)

@CoolPlayLin this is because the [`ReleaseDate: 2022-12-07`](https://github.com/microsoft/winget-pkgs/blob/c31c33b069835090007823476e89226c780ee647/manifests/p/Python/Python/3/12/3.12.0a5/Python.Python.3.12.installer.yaml#L102) in the previous manifest doesn't conform to the right standard. It should be `2022-02-07`.

I'll add exception handling for this but it shouldn't be like that anyway.

**Comment by CoolPlayLin** [comment]
@russellbanks 
I think you could add a feature to verify the `ReleaseDate` ?

**Comment by CoolPlayLin** [comment]
@russellbanks 
![image](https://github.com/russellbanks/Komac/assets/96709586/6845f4ec-5699-4049-bea5-25ee2070d34f)

**Comment by CoolPlayLin** [comment]
@russellbanks 
![image](https://github.com/russellbanks/Komac/assets/96709586/d897dc1d-94cc-44b8-a0a3-4866ebe7f4b2)
