### ISSUE TITLE
[Bug]: Product Codes not handled properly

### ISSUE THREAD

**Issue by Trenly** [russellbanks/Komac#268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Take a look - https://github.com/microsoft/winget-pkgs/pull/115152/files

**Comment by russellbanks** [comment]
Hey, this happens because Komac had an issue (#200) where names that had an architecture word in them were identified as architectures:

`https://www.website.com/ArmCord.exe` -> `arm`

Because of this Komac looks for a delimiter before and after architectures to be certain about it:

`https://www.website.com/ArmCord-x86.exe` -> `x86`

The URLs from that pull request don't have delimiters surrounding them, so it resorts to the architecture value in the MSI, which is `Intel`.

I'll adjust the function that identifies architectures from URLs to cover this case by considering it being at the end of the URL and followed by `.[extension]`.
