### ISSUE TITLE
[Bug]: Detects existing token on first-run

### ISSUE THREAD

**Issue by vedantmgoyal2009** [russellbanks/Komac#32]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Komac detects GitHub token, even when installed first-time on a machine:
![image](https://user-images.githubusercontent.com/83997633/214704275-1d8aa2ce-f151-4d0c-988e-bcda14355b9e.png)

Ideally, it should display - 
```
No existing token found. 

Please enter a GitHub token: <token-input>
```

**Comment by russellbanks** [comment]
Thanks for spotting! Komac gets the token asynchronously in the background and if there isn't one, it will prompt for it as soon as it can. This was a recent change and I hadn't considered the use of `komac token` on first-run so I will push a commit to change this :)

**Comment by vedantmgoyal2009** [comment]
It is still not fixed.

![image](https://user-images.githubusercontent.com/83997633/214765971-d7901762-7251-4f40-a195-07fb31177a1e.png)

**Comment by russellbanks** [comment]
Sorry, I hadn't tested it if you had a token stored but it wasn't valid. I've made some more changes to it and tested it without a token stored, with a token stored and it's invalid, and with a valid token, and they all work. For `komac token`, so that there's no hanging or waiting, it will ask the uesr if they want to change the currently stored token if there is one stored, without checking whether the currently stored one is invalid. It will check if it's valid before it's needed in any of the other commands.

**Comment by vedantmgoyal2009** [comment]
I haven't stored any token yet, still this prompt. It should directly ask for `Enter a GitHub token:`.
![image](https://user-images.githubusercontent.com/83997633/214866429-f6028edb-dbf7-424f-915f-4abe7f742444.png)

**Comment by russellbanks** [comment]
Could you check you have a build of the latest commit and that you don't have an entry in Windows Credentials? When I delete Komac's entry in Windows Credentials, I get the prompt `Please enter your GitHub personal access token:` when using `java -jar Komac-0.9.0-all.jar token`.

You can access Windows Credentials by searching Credential Manager > Windows Credentials > Look for `komac/github-access-token`
