### ISSUE TITLE
[Feature/Idea]: Support lowercase -v for version when no subcommand is supplied

### ISSUE THREAD

**Issue by aaronliu0130** [russellbanks/Komac#409]
### What would you like to see changed/added?

Currently, if no subcommand is provided and one types -v, they get an error, as the version switch is now -V. This change feels like it has no use: it's not like you can combine it with another subcommand either. I propose to eliminate the -V switch and replace it with -v only in the case where

**Comment by russellbanks** [comment]
[Clap](https://github.com/clap-rs/clap), the library Komac uses for command line argument parsing, defaults to `-V` rather than `-v` to not conflict with the common usage of `-v` being a verbose flag - https://github.com/clap-rs/clap/issues/138. As Komac, doesn't use a verbose flag, I can override it so that `-v`, `-V` and `--version` are all valid options.
