### ISSUE TITLE
[Bug]: Tags getting cut off on dashes

### ISSUE THREAD

**Issue by sitiom** [russellbanks/Komac#410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

```
> Tags: rust, winget, winget-cli, winget-pkgs
```

Output:
```yaml
Tags:
- cli
- pkgs
- rust
- winget
```

**Comment by russellbanks** [comment]
Hi @sitiom, this makes sense as the input is split by non-alphanumeric characters. In this, the `-` character is seen as a delimiter which is why you have a `cli` tag. This is the same with #412 where the `+` is seen as a delimiter.

I'll change this to split the input by a set of defined delimiters instead. I'm thinking just `,` and ` `.

**Comment by russellbanks** [comment]
Fixed in https://github.com/russellbanks/Komac/commit/def1eb5587460e64d23ca11802f7603b61662ce9:

```
> Tags: rust, winget, winget-cli, winget-pkgs
```
```yaml
Tags:
- rust
- winget
- winget-cli
- winget-pkgs
```
