### ISSUE TITLE
[Bug]: Unsupported file extension

### ISSUE THREAD

**Issue by Exorcism0666** [russellbanks/Komac#450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/russellbanks/Komac/assets/46537034/778307fb-3c43-404d-8d34-6cd2a649d55f)

**Comment by russellbanks** [comment]
This is because at that URL, the [`content-disposition`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition) header is `attachment; filename=""` which is not what it should have at all. This makes Komac think it doesn't have a file name and doesn't know what file type it's working with. To get around this, I'll check whether the filename is empty and use the existing fallback mechanism if it is.
