### ISSUE TITLE
[Bug]: called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by Exorcism0666** [russellbanks/Komac#479]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/russellbanks/Komac/assets/46537034/1eee82bb-afbf-42f8-8d00-b232b8deb667)

All logs: https://github.com/Exorcism0666/AutoPublish/actions/runs/7978627723/job/21784161875

**Comment by russellbanks** [comment]
The 2nd crash is fixed by https://github.com/russellbanks/Komac/commit/da7e5e9d0d73f020a3ecff710f67498c8eb28557. It's from a change I made today where SHA1's get removed from release notes. I use a fixed size string for this but didn't check for hashes greater than 40 characters, which meant it tried to add another character to the string when it's at its capacity.

**Comment by russellbanks** [comment]
The 1st crash was because Komac was trying to find the previous relative file path in the zip and couldn't find it because the folder name inside the zip had changed (`Quaternion-0.0.95.1/quaternion.exe` to `Quaternion-0.0.96.1/quaternion.exe`). I've changed it so that if this is the case, it will search for just `quaternion.exe` and then use the path to that exe as the new relative file path.
