### ISSUE TITLE
[Bug]: Another Unsupported file extension issue

### ISSUE THREAD

**Issue by OfficialEsco** [russellbanks/Komac#529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Similar to https://github.com/russellbanks/Komac/issues/468

```
./KomacPortable-linux-x64 update -i Deezer.Deezer -v 6.0.80 -u https://www.deezer.com/desktop/download/artifact/win32/x86/6.0.80
```
```
Latest version of Deezer.Deezer: 6.0.30
Error: 
   0: Unsupported file extension 80
```

**Comment by russellbanks** [comment]
Thanks for reporting! The current way for getting the file name (and subsequently the file extension) works like this:

1. Check the [Content Disposition](https://developer.mozilla.org/docs/Web/HTTP/Headers/Content-Disposition) header for `filename="file.ext"`
2. If there's no Content Disposition header or it's invalid, get the last part of the URL
3. If the last part of the URL does not have an extension, get the last part of the redirected URL if the URL redirects

For this URL, the last part is `6.0.80` and so the 'extension' is being returned as `80`. I've changed it now so that it checks whether extension it returns is a valid installer extension and if not, it goes to the next step which is getting the last part of the redirected URL. In this case, that is `long-part-of-url/win32/x86/6.0.80/DeezerDesktopSetup_6.0.80.exe`, meaning the file extension returns properly as `DeezerDesktopSetup_6.0.80.exe`.
