### ISSUE TITLE
[Bug]: fatal alert HandshakeFailure

### ISSUE THREAD

**Issue by OfficialEsco** [russellbanks/Komac#531]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

```
./KomacPortable-linux-x64 update -i fasm.fasm -v 1.73.32 -u https://flatassembler.net/fasmw17330.zip
```
```
Latest version of fasm.fasm: 1.73.30
Error: 
   0: Failed to GET from 'https://flatassembler.net/fasmw17330.zip'
   1: error sending request for url (https://flatassembler.net/fasmw17330.zip): error trying to connect: received fatal alert: HandshakeFailure
   2: error trying to connect: received fatal alert: HandshakeFailure
   3: received fatal alert: HandshakeFailure
```

**Comment by russellbanks** [comment]
Thanks for reporting! This was due to the TLS client for operating systems other than Windows and macOS using [rustls](https://github.com/rustls/rustls). rustls is a pretty nice library in that its TLS implementation is written in 100% Rust but my understanding is that they deliberately don't implement some stuff in an attempt to be more secure - https://github.com/rustls/rustls/issues/512, [rustls/manual/_02_tls_vulnerabilities](https://docs.rs/rustls/0.23.3/rustls/manual/_02_tls_vulnerabilities/index.html). Therefore, I've swapped to use OpenSSL instead which fixes this issue, #530, and #528.
