### ISSUE TITLE
[Bug]: 2 installer links, same architecture

### ISSUE THREAD

**Issue by vikingnope** [russellbanks/Komac#573]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When doing `Komac new` and adding 2 or more installer links, the program decides to give them both or all the same architecture 'x86', could we either have it so that we tell the program what architecture it is, or it detects it automatically?

**Comment by russellbanks** [comment]
Komac does detect architectures automatically but sometimes installers incorrectly record what architecture they are so Komac has fallback mechanisms.

Could you possible provide what URLs you used so I can take a look at the installers?

**Comment by vikingnope** [comment]
https://epa.gov/system/files/other-files/2023-08/swmm524(x86)_setup.exe

https://epa.gov/system/files/other-files/2023-08/swmm524(x64)_setup.exe

As you can see here with the first commit they were the same architecture: https://github.com/microsoft/winget-pkgs/pull/149612/commits/becb8e63e9a80e5772adcc945c1a2a037f719382

After I had to do another commit to fix that: https://github.com/microsoft/winget-pkgs/pull/149612/commits/1eb5c0da0412743858abfcebdd460dfca8723448

**Comment by russellbanks** [comment]
Thanks for providing the URLs. Komac finds architectures in URLs by first looking for a known architecture (E.g. x64) surrounded by delimiters. It does this because otherwise it would identify apps like [ArmCord](https://github.com/ArmCord/ArmCord) as always being the `arm` architecture.

In this case, brackets weren't in the delimiters it looks for so it checks what architecture the exe says it is, which is x86 (All Inno installers do). I've fixed this by adding brackets as delimiters to look for in a URL.

**Comment by vikingnope** [comment]
Thanks a lot
