### ISSUE TITLE
[Bug]: RelativeFilePath not updated in current nightly build

### ISSUE THREAD

**Issue by a-mnich** [russellbanks/Komac#634]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the current nightly build the RelativeFilePath doesn't seem to be correctly updated.  
I only experienced this with a single package linked below and wasn't able to find another package where I can reproduce this issue.  
With komac 2.2.1 it still works as usual.

```
komac-nightly-x86_64-pc-windows-msvc.exe update --version 2.10.1 --urls https://github.com/EdgeTX/edgetx/releases/download/v2.10.1/edgetx-cpn-win64-v2.10.1.zip --dry-run EdgeTX.Companion
```
Komac nightly:  
![grafik](https://github.com/russellbanks/Komac/assets/56564725/8f9b6140-cd76-40c6-824d-92c9ba8c6eb4)

Komac 2.2.1:  
![grafik](https://github.com/russellbanks/Komac/assets/56564725/71b424c0-080b-41de-8589-1fc0111d0d10)

**Comment by russellbanks** [comment]
Thanks for reporting! I've changed it so that if the file name or path changes within the zip, a [levenshtein](https://en.wikipedia.org/wiki/Levenshtein_distance) string comparison (returns the minimum number of insertions, deletions, and substitutions required to change one string into the other) is done to find the file path that is the most similar.
