### ISSUE TITLE
[Bug]: Lyx won't update with an error

### ISSUE THREAD

**Issue by vikingnope** [russellbanks/Komac#733]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The following error is displayed:

![image](https://github.com/user-attachments/assets/5a1bfcc5-f7a9-4019-8aa6-f3b0502a0dbd)

**Comment by russellbanks** [comment]
This is because the `Moniker` of the [previous manifest](https://github.com/microsoft/winget-pkgs/blob/0d5e0881fa6af75926b894dcca1ce5a67d0c3d9b/manifests/l/LyX/LyX/2.3.5.2/LyX.LyX.locale.en-US.yaml#L20) has a value of `""`. In the [winget schema](https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json), monikers have a minumum length of 1, so this shouldn't have passed validation and been accepted into the repository. However, the last change to the manifest was 2 years ago so winget-pkgs' automatic validation will have likely improved since then.

Therefore, this issue shouldn't apply to any other package in the repository and in terms of updating it, would be fixed permanently by removing the moniker entry in the locale schema manually.

Specifically this package though doesn't appear to be able to be updated anyway - https://github.com/microsoft/winget-pkgs/pull/166631#issuecomment-2273963355.

**Comment by vikingnope** [comment]
Ah ok thanks a lot
