### ISSUE TITLE
[Feature/Idea]: Don't require `--submit` in CI environments

### ISSUE THREAD

**Issue by vedantmgoyal2009** [russellbanks/Komac#79]
### What would you like to see changed/added?

Don't require `--submit` parameter when Komac is running when `CI` environment variable is true.

**Comment by russellbanks** [comment]
One of my considerations with this is that the default when the `CI` environment variable is true, the default is to write it in the current directory. I think this is still ideal because that means you could have access to it and for example, commit the files manually with Git.

Requiring --submit is also more explicit. If for whatever reason that the `CI` environment variable is set to true in an environment that it shouldn't, it's a bit destructive to default to automatically creating a pull request

**Comment by russellbanks** [comment]
Closing for reason above. Let me know if there's anything I haven't thought of and I'll reconsider.
