### ISSUE TITLE
[Bug]: arm64 msi detected as x64

### ISSUE THREAD

**Issue by mivsvit** [russellbanks/Komac#793]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Mattermost `arm64` wix installer at https://github.com/mattermost/desktop/releases/tag/v5.9.0 gets detected by komac as `x64`

Expected: `Architecture: arm64`

```
> wget https://releases.mattermost.com/desktop/5.9.0/mattermost-desktop-5.9.0-win-arm64.msi

2024-08-31 20:02:52 (34.9 MB/s) - 'mattermost-desktop-5.9.0-win-arm64.msi' saved [91701248/91701248]

> komac analyse mattermost-desktop-5.9.0-win-arm64.msi
InstallerLocale: en-US
Architecture: x64
InstallerType: wix
InstallerUrl: https://www.example.com/
InstallerSha256: 2A13566E780CCAED7A944C974AE547E7B045D2A4D25602740D210AECE3F028C8
ProductCode: '{91E31A20-A266-45F0-A400-7A099F456ADE}'
AppsAndFeaturesEntries:
- DisplayName: Mattermost
  Publisher: Mattermost, Inc.
  DisplayVersion: 5.9.0.0
  ProductCode: '{91E31A20-A266-45F0-A400-7A099F456ADE}'
  UpgradeCode: '{0F183CAA-DF79-5400-A71F-684F563AF31C}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\mattermost-desktop'
  ```

**Comment by russellbanks** [comment]
This is because the installer declares itself as being x64:

![{E3C469AA-3899-4C03-A2AE-1A61319DAF9E}](https://github.com/user-attachments/assets/3e46e130-ca95-48d0-b890-b57c49ac4efc)

The analyse command is purely analysis on the installer itself and therefore doesn't have the context of the installer URL. If this installer was used to update a package, komac would identify the architecture from the URL as being arm64. There isn't a point to getting the architecture from the file name for the analyse command because I created it to test komac against different installers.
