### ISSUE TITLE
[Bug]: MSI should default to x86 if platform value is empty

### ISSUE THREAD

**Issue by solomoncyj** [russellbanks/Komac#808]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/user-attachments/assets/5c9af27e-9ad5-447d-8576-eaa62d073514)

if it cannot be found, komac should ask the user

**Comment by russellbanks** [comment]
Thanks for reporting. This is because there is no platform value in the MSI:

![{88141399-EB43-4D1F-8AAE-E0695F01CB88}](https://github.com/user-attachments/assets/b226d375-54b1-4ebf-885f-d76ef3c34051)

According to [Microsoft's documentation](https://learn.microsoft.com/en-us/windows/win32/msi/template-summary#remarks) however, it should default to x86 if no platform is specified:
> If the platform specification is missing in the **Template Summary** property value, the installer assumes the Intel architecture.

I'll make this change to komac to default to x86 if no platform is specified.

**Comment by solomoncyj** [comment]
Dont. Kost apps nowadays only support x64. It should default to that instead

**Comment by russellbanks** [comment]
> Dont. Kost apps nowadays only support x64. It should default to that instead

Microsoft's documentation states that MSI installers install in x86 mode if the platform value is missing. x86 applications can still install on x64 devices.
