### ISSUE TITLE
[Bug]: False positive virus?

### ISSUE THREAD

**Issue by sitiom** [russellbanks/Komac#95]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Tried `v1.0.2` today, and upon running Komac, this happened:

![image](https://user-images.githubusercontent.com/56180050/218605238-f62a9adb-4884-4228-96b6-391796935105.png)

Any way we can mitigate this?

**Comment by russellbanks** [comment]
I usually submit every release of Komac (or my other programs) to Microsoft as a false positive as Komac is unsigned. They do a scan of it and within a few hours, those flag-ups get removed (as long as you're on the latest Windows defender security definition version). I'm quite busy this week so I haven't had a chance to do it. 1.0.2 was made as a quick patch release with #91, otherwise I would have waited until I was more free later on in the week.

**Comment by russellbanks** [comment]
I've submitted all of Komac's versions so far to Microsoft as false positives and will continue to do so on each release.
