### ISSUE TITLE
[Bug]: Invalid Display Name

### ISSUE THREAD

**Issue by raypappa** [russellbanks/Komac#975]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Generated manifest is invalid
I ran this command
```shell
komac update -v 259.241213.0 -u https://github.com/tutao/tutanota/releases/download/tutanota-desktop-release-259.241213.0/tutanota-desktop-win.exe -- Tutanota.Tutanota
```

which produced the following in `Tutanota.Tutanota.installer.yaml`
```
AppsAndFeaturesEntries:
- DisplayName: "Tuta Mail 259.241213.0\x03肁"
```

```
$ komac analyse tutanota-desktop-win.exe
InstallerLocale: en-US
Architecture: x86
InstallerType: nullsoft
InstallerUrl: https://example.com/
InstallerSha256: 9D1DB1545BBDE114ECBE339B71F84A41E58F807224429D929C1D1CE6CF67DC2C
AppsAndFeaturesEntries:
- DisplayName: "Tuta Mail 220.240411.0\x03肁"
  Publisher: Tutao GmbH
  DisplayVersion: 220.240411.0
```

I'm not even sure where the DisplayName is being captured from nullsoft. I don't see anywhere those characters are in tuta's repo

**Comment by russellbanks** [comment]
Thanks for the issue!

This is because NSIS has different ways of parsing strings based on whether it's NSIS version 2 or NSIS version 3. In the PE manifest, it's defined as `Nullsoft Install System v27-Nov-2019.cvs`. The existing code parses this as `2.7.2`, which is very clearly wrong, so I'll make that code stricter as I expect something like `Nullsoft Install System v3.10` usually.
